stages:
  - install
  - test
  - containerize
  - verify
  - release
  - pages

include:
  - component: gitlab.com/components/container-scanning/container-scanning@5.2.0
    inputs:
      stage: verify
      # Change image name to match our repository naming convention
      cs_image: $CI_REGISTRY_IMAGE
      enable_mr_pipelines: false
  - component: gitlab.com/components/dependency-scanning/main@2.0.0
    inputs:
      stage: verify
      job_name: dependency_scanning
      disabled_resolution_jobs: maven,gradle,python
  - component: $CI_SERVER_FQDN/TIBHannover/gitlab-ci-components/pipeline-trigger-orkg@0.0.9
    inputs:
      component_name: orkg-frontend
      needs:
        - job: docker-build
          optional: true
        - job: docker-build-default-branch
          optional: true
  - component: $CI_SERVER_FQDN/TIBHannover/gitlab-ci-components/docker-build@0.0.9
    inputs:
      oci_image_vendor: $DOCKER_IMAGE_OCI_VENDOR
  - component: $CI_SERVER_FQDN/TIBHannover/gitlab-ci-components/docker-tag-release@0.0.9

install:
  image: node:24-bookworm
  stage: install
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

vitest:
  image: node:24-bookworm
  stage: test
  script:
    - cp default.env .env
    - npm run test:ci
  artifacts:
      when: always
      reports:
        junit:
          - junit.xml

dependency_scanning:
  needs: []
  rules:
    - if: '$CI_COMMIT_BRANCH || $CI_COMMIT_TAG'

# deploy storybook to Gitlab pages
pages:
  image: node:24-bookworm
  stage: pages
  script:
    - rm -rf public # remove the currently existing 'public' folder that contains static files for running the frontend
    - mkdir -p public/storybook
    - npm run build-storybook
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
