// PDF annotation
export const PDF_ANNOTATION_SELECT_TOOL = 'PDF_ANNOTATION_SELECT_TOOL';
export const PDF_ANNOTATION_SET_TABLE_DATA = 'PDF_ANNOTATION_SET_TABLE_DATA';
export const PDF_ANNOTATION_UPDATE_TABLE_DATA = 'PDF_ANNOTATION_UPDATE_TABLE_DATA';
export const PDF_ANNOTATION_SET_LABEL_CACHE = 'PDF_ANNOTATION_SET_LABEL_CACHE';
export const PDF_ANNOTATION_SET_TABLE_REGION = 'PDF_ANNOTATION_SET_TABLE_REGION';
export const PDF_ANNOTATION_DELETE_TABLE_REGION = 'PDF_ANNOTATION_DELETE_TABLE_REGION';
export const PDF_ANNOTATION_FETCH_PDF_PARSE_REQUEST = 'PDF_ANNOTATION_FETCH_PDF_PARSE_REQUEST';
export const PDF_ANNOTATION_FETCH_PDF_PARSE_FAILURE = 'PDF_ANNOTATION_FETCH_PDF_PARSE_FAILURE';
export const PDF_ANNOTATION_FETCH_PDF_PARSE_SUCCESS = 'PDF_ANNOTATION_FETCH_PDF_PARSE_SUCCESS';
export const PDF_ANNOTATION_FETCH_PDF_CONVERT_REQUEST = 'PDF_ANNOTATION_FETCH_PDF_CONVERT_REQUEST';
export const PDF_ANNOTATION_FETCH_PDF_CONVERT_FAILURE = 'PDF_ANNOTATION_FETCH_PDF_CONVERT_FAILURE';
export const PDF_ANNOTATION_FETCH_PDF_CONVERT_SUCCESS = 'PDF_ANNOTATION_FETCH_PDF_CONVERT_SUCCESS';
export const PDF_ANNOTATION_RESET_DATA = 'PDF_ANNOTATION_RESET_DATA';
