export const UPFATE_GENERAL_DATA = 'UPFATE_GENERAL_DATA';
export const ADD_PAPER_NEXT_STEP = 'ADD_PAPER_NEXT_STEP';
export const ADD_PAPER_PREVIOUS_STEP = 'ADD_PAPER_PREVIOUS_STEP';
export const UPDATE_RESEARCH_FIELD = 'UPDATE_RESEARCH_FIELD';
export const CREATE_CONTRIBUTION = 'CREATE_CONTRIBUTION';
export const DELETE_CONTRIBUTION = 'DELETE_CONTRIBUTION';
export const SELECT_CONTRIBUTION = 'SELECT_CONTRIBUTION';
export const UPDATE_RESEARCH_PROBLEMS = 'UPDATE_RESEARCH_PROBLEMS';

export const CREATE_RESOURCE = 'CREATE_RESOURCE';
export const DELETE_RESOURCE = 'DELETE_RESOURCE';
export const CREATE_PROPERTY = 'CREATE_PROPERTY';
export const DELETE_PROPERTY = 'DELETE_PROPERTY';
export const CREATE_VALUE = 'CREATE_VALUE';
export const DELETE_VALUE = 'DELETE_VALUE';