// Add paper

export const UPFATE_GENERAL_DATA = 'UPFATE_GENERAL_DATA';
export const ADD_PAPER_NEXT_STEP = 'ADD_PAPER_NEXT_STEP';
export const ADD_PAPER_PREVIOUS_STEP = 'ADD_PAPER_PREVIOUS_STEP';
export const ADD_PAPER_BLOCK_NAVIGATION = 'ADD_PAPER_BLOCK_NAVIGATION';
export const ADD_PAPER_UNBLOCK_NAVIGATION = 'ADD_PAPER_UNBLOCK_NAVIGATION';
export const UPDATE_RESEARCH_FIELD = 'UPDATE_RESEARCH_FIELD';
export const CREATE_CONTRIBUTION = 'CREATE_CONTRIBUTION';
export const DELETE_CONTRIBUTION = 'DELETE_CONTRIBUTION';
export const SELECT_CONTRIBUTION = 'SELECT_CONTRIBUTION';
export const UPDATE_CONTRIBUTION_LABEL = 'UPDATE_CONTRIBUTION_LABEL';
export const UPDATE_RESEARCH_PROBLEMS = 'UPDATE_RESEARCH_PROBLEMS';
export const UPDATE_ABSTRACT = 'UPDATE_ABSTRACT';
export const CREATE_ANNOTATION = 'CREATE_ANNOTATION';
export const REMOVE_ANNOTATION = 'REMOVE_ANNOTATION';
export const VALIDATE_ANNOTATION = 'VALIDATE_ANNOTATION';
export const UPDATE_ANNOTATION_CLASS = 'UPDATE_ANNOTATION_CLASS';
export const CLEAR_ANNOTATIONS = 'CLEAR_ANNOTATIONS';

export const CLOSE_TOUR = 'CLOSE_TOUR';
export const OPEN_TOUR = 'OPEN_TOUR';
export const UPDATE_TOUR_CURRENT_STEP = 'UPDATE_TOUR_CURRENT_STEP';

export const CREATE_RESOURCE = 'CREATE_RESOURCE';
export const DELETE_RESOURCE = 'DELETE_RESOURCE';
export const CREATE_PROPERTY = 'CREATE_PROPERTY';
export const DELETE_PROPERTY = 'DELETE_PROPERTY';
export const CREATE_VALUE = 'CREATE_VALUE';
export const DELETE_VALUE = 'DELETE_VALUE';
export const TOGGLE_PROPERTY_COLLAPSE = 'TOGGLE_PROPERTY_COLLAPSE';
export const TOGGLE_EDIT_VALUE = 'TOGGLE_EDIT_VALUE';
export const UPDATE_VALUE_LABEL = 'UPDATE_VALUE_LABEL';

export const SELECT_RESOURCE = 'SELECT_RESOURCE';
export const ADD_RESOURCE_HISTORY = 'ADD_RESOURCE_HISTORY';
export const GOTO_RESOURCE_HISTORY = 'GOTO_RESOURCE_HISTORY';
export const CLEAR_RESOURCE_HISTORY = 'CLEAR_RESOURCE_HISTORY';
export const CLEAR_SELECTED_PROPERTY = 'CLEAR_SELECTED_PROPERTY';
export const ADD_FETCHED_STATEMENT = 'ADD_FETCHED_STATEMENT';
export const SET_STATEMENT_IS_FECHTED = 'SET_STATEMENT_IS_FECHTED';
export const SAVE_ADD_PAPER = 'SAVE_ADD_PAPER';
export const SET_RESEARCH_PROBLEMS = 'SET_RESEARCH_PROBLEMS';
export const IS_FETCHING_STATEMENTS = 'IS_FETCHING_STATEMENTS';
export const DONE_FETCHING_STATEMENTS = 'DONE_FETCHING_STATEMENTS';
export const RESET_LEVEL = 'RESET_LEVEL';
export const RESET_STATEMENT_BROWSER = 'RESET_STATEMENT_BROWSER';

export const ADD_TO_COMPARISON = 'ADD_TO_COMPARISON';
export const REMOVE_FROM_COMPARISON = 'REMOVE_FROM_COMPARISON';
export const LOAD_COMPARISON_FROM_COOKIE = 'LOAD_COMPARISON_FROM_COOKIE';
