import { CLASSES } from '@/constants/graphSettings';
import ROUTES from '@/constants/routes';
import { Certainty, Visibility, VisibilityFilter } from '@/services/backend/types';

const CONTENT_TYPES: string[] = [
    CLASSES.PAPER,
    CLASSES.CONTRIBUTION,
    CLASSES.COMPARISON,
    CLASSES.LITERATURE_LIST_PUBLISHED,
    CLASSES.SMART_REVIEW_PUBLISHED,
    CLASSES.VISUALIZATION,
    CLASSES.PROBLEM,
];

export const VISIBILITY_FILTERS: { [key: string]: VisibilityFilter } = {
    TOP_RECENT: 'combined',
    ALL_LISTED: 'ALL_LISTED',
    UNLISTED: 'UNLISTED',
    FEATURED: 'FEATURED',
    NON_FEATURED: 'NON_FEATURED',
    DELETED: 'DELETED',
} as const;

export const VISIBILITY: { [key: string]: Visibility } = {
    DEFAULT: 'DEFAULT',
    FEATURED: 'FEATURED',
    UNLISTED: 'UNLISTED',
    DELETED: 'DELETED',
};

export const CERTAINTY: { [key: string]: Certainty } = {
    LOW: 'LOW',
    MODERATE: 'MODERATE',
    HIGH: 'HIGH',
};

export const CONTENT_TYPES_WITH_SPECIAL_SCHEMA: string[] = [
    CLASSES.PAPER,
    CLASSES.PAPER_VERSION,
    CLASSES.COMPARISON,
    CLASSES.COMPARISON_PUBLISHED,
    CLASSES.SMART_REVIEW,
    CLASSES.SMART_REVIEW_PUBLISHED,
    CLASSES.LITERATURE_LIST,
    CLASSES.LITERATURE_LIST_PUBLISHED,
    CLASSES.NODE_SHAPE,
    CLASSES.ROSETTA_NODE_SHAPE,
    CLASSES.RESEARCH_FIELD,
];

export const CREATE_NEW_RESOURCE_CONTENT_TYPES: { [key: string]: string } = {
    [CLASSES.PAPER]: ROUTES.CREATE_PAPER,
    [CLASSES.COMPARISON]: ROUTES.CREATE_COMPARISON,
    [CLASSES.COMPARISON_PUBLISHED]: ROUTES.CREATE_COMPARISON,
    [CLASSES.SMART_REVIEW]: ROUTES.REVIEW_NEW,
    [CLASSES.SMART_REVIEW_PUBLISHED]: ROUTES.REVIEW_NEW,
    [CLASSES.LITERATURE_LIST]: ROUTES.LIST_NEW,
    [CLASSES.LITERATURE_LIST_PUBLISHED]: ROUTES.LIST_NEW,
    [CLASSES.NODE_SHAPE]: ROUTES.ADD_TEMPLATE,
    [CLASSES.ROSETTA_NODE_SHAPE]: ROUTES.RS_ADD_TEMPLATE,
};

export default CONTENT_TYPES;
