const THING_TYPES: {
    [key: string]: string;
} = {
    COMPARISON: 'COMPARISON',
    DIAGRAM: 'DIAGRAM',
    VISUALIZATION: 'VISUALIZATION',
    DRAFT_COMPARISON: 'DRAFT_COMPARISON',
    LIST: 'LIST',
    REVIEW: 'REVIEW',
    QUALITY_REVIEW: 'QUALITY_REVIEW',
    PAPER_VERSION: 'PAPER_VERSION',
    UNKNOWN: 'UNKNOWN',
};

export default THING_TYPES;
